[package]
name = "pulso"
version = "0.1.0"
description = "Pulso: tiempo, tareas y uso de IA de tu equipo"
authors = ["Equipo Pulso"]
license = ""
repository = "https://github.com/StehvenObandoUcc/app-escritorio"
edition = "2024"
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pulso_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1", features = [] }
tauri-plugin-log = "2"
rusqlite = { version = "0.40.2", features = ["bundled"] }
aes-gcm = "0.11.1"
keyring = "4.2.0"
uuid = { version = "1.27.0", features = ["v4"] }
chrono = "0.4.45"
tauri-plugin-notification = "2.5.1"

[target."cfg(windows)".dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_Threading", "Win32_System_SystemInformation", "Win32_UI_Accessibility", "Win32_System_Com", "Win32_System_Variant", "Win32_System_Ole", "Win32_System_Registry"] }
